<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SatelliteResourceLanguages>es</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SltCsharpMetrics\SltCsharpMetrics.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Input\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Expected\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
